### ISSUE TITLE
example runfiles

### ISSUE THREAD

**Issue by thirtyeggs** [timmassingham/simNGS#3]
Hi,
Can I ask the difference among the example runfiiles under http://www.ebi.ac.uk/goldman-srv/simNGS/runfiles5?
The HiSeq runfiles follow the rule s_<Num1>_<Num2>x.runfile and the 151 cycle GAII  runfiles follow the rule s_<Num3>_<Num4>.runfile.
Can you tell me the meaning of each NumX?
Thank you for your help in advance.

Yun

**Comment by timmassingham** [comment]
They are where the data was trained from.  For the GAII runs, the numbers
and lane then tile.  For the HiSeq runs, I only had access to decimated
data; the first number refers to the channel, the 4x refers to tiles 40 to
49.

**Comment by thirtyeggs** [comment]
Thank you for your clarification!
